### ISSUE TITLE
Running the tool (as a newbie)

### ISSUE THREAD

**Issue by vpraturlon** [nkons/r2rml-parser#11]
I'd like to use the tool to publish DSpace data as per examples.
Does the tool need to modify the DSpace db / setup?
(should it run in the DSpace host?)

**Comment by nkons** [comment]
The tool needs JDBC connectivity with the DSpace database. This does not mean that the tool has to run in the same host necessarily, but, usually, for security reasons, JDBC connection is only allowed from the same host (localhost). So in theory, it can run from anywhere, but it is good practice to run it from the same host.

The DSpace installation remains unaltered, nothing needs to be done there. Also, the tool does not modify anything in DSpace, it only performs SELECT queries.

How to configure JDBC connectivity:
From the tool properties, in the file r2rml.properties, locate the properties:
db.url, db.login, db.password, and db.driver

These have to be in accordance with the ones in your DSpace instance:
File config/dspace.cfg, properties:
db.url, db.username, db.password, and db.driver.

**Comment by Gautamshahi** [comment]
After changing the JDBC connection properties, how to run the r2ml parser? Do I need to import the entire project in an IDE to execute it? @vpraturlon can you give hint?
