### ISSUE TITLE
include xsd:type in field

### ISSUE THREAD

**Issue by jorgeakanieves** [nkons/r2rml-parser#15]
I use this succesful project r2rml parser to generate rdf as from r2rml file and an oracle table.

The problem is that I generate rdf but without type specificatios...
In my r2rml I have this map for example: 

    rr:predicateObjectMap [
        rr:predicate gr:valueAddedTaxIncluded;
        rr:objectMap [
            rr:constant "true"; rr:datatype xsd:boolean;
        ];
    ];

But when I get the rdf file, the datatype boolean is not included:

<http://example.com/Contract/66954/budgetPrice> <http://purl.org/goodrelations/v1#valueAddedTaxIncluded> "true" .

it should be:

<http://example.com/Contract/66954/budgetPrice> <http://purl.org/goodrelations/v1#valueAddedTaxIncluded> "true" ^^xsd:boolean.

any help?

**Comment by nkons** [comment]
It seems that there is an issue with the Jena serializer to TURTLE.

Using your mapping and choosing the RDF/XML syntax (property jena.destinationFileSyntax in r2rml.properties), I have the result

      <rdf:Description rdf:about="...">
        <gr:valueAddedTaxIncluded rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</gr:valueAddedTaxIncluded>
      </rdf:Description>

but when I change the syntax to TURTLE (jena.destinationFileSyntax=TURTLE) the output is not correct.

What syntax do you use for the result model?

**Comment by nkons** [comment]
UPDATE: I read here

http://www.w3.org/TR/turtle/#booleans

that booleans are a special case.

So, in turtle syntax, the correct output is

    http://example.com/Contract/66954/budgetPrice http://purl.org/goodrelations/v1#valueAddedTaxIncluded true

(without the quotes and the ^^xsd:boolean in the end).

**Comment by jorgeakanieves** [comment]
But It is my understanding that I should include all the dataType for each field in the rdf file...

This are some of my r2rml.properties: 
mapping.file.type=TURTLE
input.model.type=RDF/XML
jena.destinationFileSyntax=N3

Not only boolean but also float or datetime

Is it right?

**Comment by nkons** [comment]
Yes, you are right, the dataType should be included for each field in the rdf file. If no datatype is defined, the default is xsd:string.

My point is that with e.g. date, the serialization in turtle will be
    ex:subject ex:prop "2015-05-01"^^xsd:date
and you have the type serialized explicitly: `^^xsd:date` but with booleans, you will not have the `^^xsd:boolean` at the end or the quotes around `true`.

**Comment by jorgeakanieves** [comment]
Thanks nkons. 

It there any option to include the datatype from the r2rml parser tool?

**Comment by nkons** [comment]
Not sure I understand the question. Could you please be more specific or give an example?

**Comment by jorgeakanieves** [comment]
sorry nkons, I mean that if is it possible to include the datatype description into the rdf triples as it:

dump.rdf example:

<https://servicios.aragon.es/rdf/Contract/66954/budgetPrice> <http://purl.org/goodrelations/v1#valueAddedTaxIncluded> "true" ^^xsd:boolean.

<https://servicios.aragon.es/rdf/Contract/66954/budgetPrice> <http://purl.org/goodrelations/v1#hasCurrencyValue> "9643.72"^^xsd:float .

**Comment by nkons** [comment]
In Turtle syntax, no, datatype is not included explicitly in the output for boolean and float. However, the output is valid.

If you have to include the datatype, you will have to choose another serialization format for the output RDF graph, e.g. RDF/XML.

Now, for the other issue you mention, did you try to include in the R2RML mapping file a declaration `rr:termType rr:IRI` for this object map?

**Comment by jorgeakanieves** [comment]
Thanks nkons, I know that include the dataType is not neccesary but it´s better anyway..

By the other hand, sometimes the generator includes the "<" and ">" for the uri in the object map but not always..It´s peculiar

I write it as rr:template:

    rr:predicateObjectMap [
        rr:predicate pproc:procedureType;
        rr:objectMap [
            rr:template "http://contsem.unizar.es/def/sector-publico/pproc#{as_procedimiento}";
        ];
    ];

**Comment by nkons** [comment]
You will have to define the termType explicitly. I believe if you change it as follows it will work. If not, please let me know.

    rr:objectMap [
             rr:template "https://example.com/Contract/{ID}/ContractActivities"; rr:termType rr:IRI;
    ];

**Comment by jorgeakanieves** [comment]
Yes, it works nkons :)
