### ISSUE TITLE
rr:parentTriplesMap result in error when rr:child is a literal

### ISSUE THREAD

**Issue by ValeriaPequeno** [nkons/r2rml-parser#17]
Hi,

When I trie pick up a uri from another r2rml mapping give me a error:

I thing the problem is the rr:child in the rr:parentTripleMap is a string and the query to pick up the tuple in the database is not properly formed.

Example of my mapping:

map:Organization
	rr:logicalTable [ rr:sqlQuery """
		SELECT OrgID AS ID, Homepage AS foaf_homepage, Name AS rdfs_label, Address AS vcard_ADR, Location AS vcard_ADR2, Postcode AS vcard_ADR3, Country AS vcard_ADR4 
		FROM organizations
	""" ];
 
	rr:subjectMap [
		rr:template 'http://data.example.com/organization/{"ID"}';
		rr:class conf:Organization; 
	];
	rr:predicateObjectMap [
		rr:predicate rdfs:label;
		rr:objectMap [ rr:column 'rdfs_label'; ]
	]; 
	rr:predicateObjectMap [
		rr:predicate foaf:homepage;
		rr:objectMap [ rr:column 'foaf_homepage' ; ] 
	];
	rr:predicateObjectMap [
		rr:predicate vcard:ADR; 
		rr:objectMap [
			rr:parentTriplesMap map:PostalAddress; 
			rr:joinCondition [
				rr:child "\"vcard_ADR\"";
				rr:parent 'Address'; 
			]
		] 
	].

when the R2RML-parser makes the query to the database, for example:
SELECT Address AS ID, 
  Location AS ID2, 
  Postcode AS ID3, 
  Country AS ID4, 
  Country AS vcard_country, 
  Address AS vcard_street, 
  Location AS vcard_locality,
  Postcode AS vcard_pcode 		
FROM organizations 	 
WHERE Address = 4676 Admirality Way

The query returns an error because there is not any ' ' in 4676 Admirality Way.

I hope this problem can be solved soon,
Best regards,
Valéria

**Comment by nkons** [comment]
Hi Valeria,

Indeed, it was a bug, that I believe is now fixed (commit 3c4cbf5). Please let me know how this goes.

In case you are not sure how to download and compile the code, see my comment on issue #16

**Comment by ValeriaPequeno** [comment]
Hi,

Thank you for your commit. However, when I put the new release to work, the following message appear:

This is R2RML Parser 0.7-alpha. Run with -h for help on options.
Exception in thread "main" java.lang.NullPointerException
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at gr.seab.r2rml.beans.Generator.createTriples(Generator.java:455)
	at gr.seab.r2rml.beans.Main.main(Main.java:104)
R2RML Parser 0.7-alpha. Done.

The same mappings in before version, works well.

The log file is in attach.

[status.txt](https://github.com/nkons/r2rml-parser/files/39974/status.txt)

Best regards,
Valeria

**Comment by nkons** [comment]
Hi Valeria, I believe commit 1b2e822 fixes this. Can you please verify?

**Comment by ValeriaPequeno** [comment]
Hi Nikolaos,

Unfortulatly the problem is not fix yet. I have done the sollowing steps:

1) synchronized my local github repository
2) refreshed my eclipse copy of r2rml-parser
3) run as maven build -> package
4) verified that the correct mapping is assigned in the property file.
5) run the generated application in the target folder.
6) The same error message appeared.

In attachment is my files.
Thanks by your effort in help me.
Best,
Valéria

**Comment by nkons** [comment]
Strange... I don't get any exceptions in mine... Please send me again the status.log after you setdefault.verbose=truein r2rml.propertiesThanks
Also, try maven build -> clean package

Date: Mon, 23 Nov 2015 02:39:23 -0800

**Comment by ValeriaPequeno** [comment]
Hi,

I did a maven clean and built the project again. After I changed the
default.verbose=true. The error message was not resolved yet.

My files are in attachment. Thanks.
Best,
Valéria

**Comment by nkons** [comment]
Hi, I believe the latest commit (6a28b95) fixes this issue. It worked for me locally; 
with the following database and mapping file, r2rml-parser produced an rdf containing 146 triples.

[iswc-postgres_dump.sql.txt](https://github.com/nkons/r2rml-parser/files/46299/iswc-postgres_dump.sql.txt)

[iswc-mapping_test.rdf.txt](https://github.com/nkons/r2rml-parser/files/46301/iswc-mapping_test.rdf.txt)

**Comment by ValeriaPequeno** [comment]
I tested and I seems fine now. Thanks.
