### ISSUE TITLE
upgrade to work with DSpace 5

### ISSUE THREAD

**Issue by helix84** [nkons/r2rml-parser#18]
DSpace 5 introduced Metadata on all DSpace objects. A consequence of the implementation is that most entity attributes moved into the ```metadatavalue``` table. Thus r2rml-parser won't work with DSpace 5 or later.

This page describes the DSpace DB schema changes:
https://wiki.duraspace.org/display/DSPACE/Metadata+for+all+DSpace+objects

**Comment by nkons** [comment]
Hi helix84,

Thanks for your interest in this tool. Although its purpose is to be a generic R2RML mapping tool, I understand its importance when it comes to extracting RDF data from popular tools such as DSpace. Hence, I have provided a new mapping file that my local tests showed does so successfully from DSpace 5. Please see commit e04dd02 and let me know if this is ok.
