### ISSUE TITLE
invalide .jar archive

### ISSUE THREAD

**Issue by pjpradeepjha** [nkons/r2rml-parser#23]
I trying to build it from source code using Eclipse on Windows 10. I have all the necessary dependencies installed. However, after importing an existing maven project i get the following error.

Description	Resource	Path	Location	Type
The container 'Maven Dependencies' references non existing library 'C:\Users\Pradeep\.m2\repository\com\oracle\ojdbc6\11.2.0.3\ojdbc6-11.2.0.3.jar'	r2rml-parser		Build path	Build Path Problem

For some reason, instead of having a .jar file at the specified location i have a .LASTUPDATED (ojdbc6-11.2.0.3.jar.lastUpdated) file over there. Changing the extension to .jar throws another error saying "invalid archive".

Screenshots.

![eclipseerror](https://cloud.githubusercontent.com/assets/25187880/23823177/d6fd4f52-0654-11e7-81d5-705b779dd40c.JPG)

![files at the location](https://cloud.githubusercontent.com/assets/25187880/23823178/d75b8fcc-0654-11e7-96a5-eae74a8c5eb2.JPG)

I'll use the binaries in the meantime and thank you for making this useful tool.

**Comment by nkons** [comment]
Hi,

Thanks for reporting this. This looks like a problem in the Oracle JDBC driver, as the one discussed in Issue #22 . So, if you are not using Oracle, you can comment out the dependency. This means that in this file
https://github.com/nkons/r2rml-parser/blob/master/pom.xml
you would have to surround with comments or remove altogether the entry:

`<dependency>`
`  <groupId>com.oracle</groupId>`
`  <artifactId>ojdbc6</artifactId>`
`  <version>11.2.0.3</version>`
`</dependency>`

And then run `mvn package` again.

If you are using Oracle, maybe you could try replacing this dependency with another, perhaps more recent one. Maybe this one would be worth a go: http://mvnrepository.com/artifact/com.oracle/ojdbc6

At the time of making the release, there was no reliable Oracle JDBC driver in the public maven repositories, so an additional repository had to be also added in pom.xml. Maybe this is not the case anymore? If so, this repository could also be commented out/deleted.

Best regards,
Nikolaos

**Comment by pjpradeepjha** [comment]
@nkons thanks. I'll try with the proposed settings. However, I got my work done using the binary. Thanks again. cheers
