### ISSUE TITLE
Hash function

### ISSUE THREAD

**Issue by fhidalgl** [nkons/r2rml-parser#27]
Hi!

I need to obtain the hash value from a table field. I am using the following instruction DBMS_CRYPTO.Hash(UTL_RAW.cast_to_raw(<FIELD>),3) which runs ok in sql plus but fails during the execution.

java.lang.StringIndexOutOfBoundsException: String index out of range: -6
	at java.lang.String.substring(String.java:1911)
	at gr.seab.r2rml.entities.sql.SelectQuery.createSelectFieldTable(SelectQuery.java:137)
	at gr.seab.r2rml.entities.sql.SelectQuery.createSelectFields(SelectQuery.java:78)

Thanks!

**Comment by nkons** [comment]
Hi, it looks like the select query parser is confused by the presence of dots in your query functions (DBMS_CRYPTO.Hash and UTL_RAW.cast_to_raw). In the select query parser, dots are expected to separate table names from fields. Is there a way to rewrite your SQL query in a way that does not contain any dots in its functions?

**Comment by fhidalgl** [comment]
Ok, do you think that an expression like this will work? 
SELECT HASH(TO_RAW('TEXT', 3)) from dual;
If so, I can try to define two private synonims for the functions.

Thanks!

**Comment by fhidalgl** [comment]
Hello,
Finally, I created a function and it worked!

CREATE OR REPLACE FUNCTION HASH (text_in IN varchar)
    RETURN VARCHAR IS
    BEGIN
        RETURN DBMS_CRYPTO.Hash(UTL_RAW.cast_to_raw(text_in),3);
    END;
/

Thank you!

**Comment by nkons** [comment]
Glad this worked.

Best,
Nikos
